### ISSUE TITLE
Create Forms and Modal

### ISSUE THREAD

**Issue by Chrissiku** [Chrissiku/p2doc-healthcare#15]
## Whats is needed
- ###  Implement Modal as on the image bellow :
     
<img width="336" alt="Screenshot 2023-12-06 at 10 37 23 AM" src="https://github.com/Chrissiku/p2doc-healthcare/assets/101924220/be25870c-fd23-48b3-a35b-9db030ad19cb">

- ### Implement doctor form as on the image bellow :
<img width="335" alt="Screenshot 2023-12-06 at 10 37 29 AM" src="https://github.com/Chrissiku/p2doc-healthcare/assets/101924220/65f59f9d-7bb5-4086-bf4e-794ee9a01ed7">

- ### implement patient form as on the image bellow
<img width="328" alt="Screenshot 2023-12-06 at 10 37 39 AM" src="https://github.com/Chrissiku/p2doc-healthcare/assets/101924220/3a574a1e-d114-4fad-98f3-e1de5a08b61f">

Figma Link : https://www.figma.com/file/B5ls4gDFUMTFGTUBh3iQOR/Untitled?type=design&node-id=0-1&mode=design&t=iTmiUyUOomIYcZbX-0

**Comment by uy-scuti100** [comment]
ill take this
